# Generated by Django 5.0.4 on 2024-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100)),
                ('aparelho', models.CharField(max_length=100)),
                ('garantia', models.BooleanField()),
                ('contato', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('descricao_problema', models.TextField()),
            ],
        ),
    ]
