# Generated by Django 5.0.4 on 2024-04-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_perfil_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
