# Generated by Django 5.0.4 on 2024-04-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_perfil_cpf_alter_perfil_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
    ]
