# Generated by Django 5.0.4 on 2024-04-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_cadfunc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadfunc',
            old_name='email',
            new_name='email_func',
        ),
        migrations.RenameField(
            model_name='cadfunc',
            old_name='senha',
            new_name='senha_func',
        ),
    ]
