# Generated by Django 5.0.4 on 2024-04-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_email_cadfunc_email_func_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('contato', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='CadFunc',
            new_name='Funcionario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='email_func',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='senha_func',
            new_name='senha',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='senha',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.funcionario'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('fechada', 'Fechada')], default='aberta', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.cliente'),
            preserve_default=False,
        ),
    ]
