# Generated by Django 5.0.4 on 2024-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_perfil_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparelho', models.CharField(max_length=255)),
                ('garantia', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')])),
                ('descricao_problema', models.CharField(max_length=255)),
            ],
        ),
    ]
