# Generated by Django 5.0.4 on 2024-04-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_ordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='perfil_os',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='apps.perfil'),
        ),
    ]
