# Generated by Django 5.0.4 on 2024-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_cliente_rename_cadfunc_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='nome_completo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
