# Generated by Django 5.0.4 on 2024-05-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_ordemservico_perfil_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('Enviada', 'Ordem de serviço enviada'), ('Iniciada', 'Ordem de serviço iniciada'), ('Em_analise', 'Em análise'), ('Aguardando_peca', 'Aguardando peça'), ('Em_conserto', 'Em conserto'), ('Pronto', 'Pronto')], default='Enviada', max_length=20),
        ),
    ]
