# Generated by Django 5.0.4 on 2024-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_ordemservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='modelo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
