# Generated by Django 5.0.4 on 2024-05-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_ordemservico_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='funcionario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsavel', to='apps.perfil'),
        ),
    ]
