# Generated by Django 5.0.4 on 2024-04-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_escolheros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='username',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='username',
        ),
    ]
