# Generated by Django 5.0.4 on 2024-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_ordemservico_funcionario_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='anotacoes_internas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='comentarios_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='problema_detectado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('Enviada', 'Ordem de serviço enviada'), ('Iniciada', 'Ordem de serviço iniciada'), ('Em_analise', 'Em análise'), ('Aguardando_peca', 'Aguardando peça'), ('Aguardando_reparo', 'Aguardando reparo'), ('Em_reparo', 'Em reparo'), ('Pronto', 'Pronto')], default='Enviada', max_length=20),
        ),
    ]
