# Generated by Django 5.0.4 on 2024-04-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_cliente_username_remove_funcionario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='senha',
            new_name='password',
        ),
    ]
