# Generated by Django 5.0.4 on 2024-04-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_rename_senha_funcionario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='responsavel',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='email',
            new_name='email_empresa',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='password',
            new_name='senha',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.DeleteModel(
            name='EscolherOs',
        ),
        migrations.DeleteModel(
            name='OrdemServico',
        ),
    ]
