# Generated by Django 5.0.4 on 2024-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_ordemservico_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_atendimento',
            field=models.CharField(choices=[('-', '-'), ('FON', 'Fora on site'), ('FB', 'Fora Balcão'), ('GS', 'Garantia serviço'), ('GB', 'Garantia balcão'), ('GON', 'Garantia on site'), ('GIN', 'Garantia instalação'), ('GRIN', 'Garantia reincidência')], default='-', max_length=4),
        ),
    ]
