# Generated by Django 5.0.4 on 2024-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_ordemservico_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='username',
            field=models.CharField(default=2, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
