# Generated by Django 5.0.4 on 2024-05-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_ordemservico_tipo_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_os/'),
        ),
    ]
