# Generated by Django 5.0.4 on 2024-05-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_ordemservico_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='perfil_os',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apps.perfil'),
        ),
    ]
