# Generated by Django 5.0.4 on 2024-05-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_ordemservico_perfil_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='comentario_avaliacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
