# Generated by Django 5.0.4 on 2024-06-07 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_ordemservico_avaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='funcionario_responsavel',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
