# Generated by Django 5.0.4 on 2024-06-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_ordemservico_funcionario_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='funcionario',
            field=models.BooleanField(),
        ),
    ]
