# Generated by Django 5.0.4 on 2024-06-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_rename_comentarios_cliente_ordemservico_mensagem_funcionario'),
        ('apps', '0018_alter_perfil_funcionario'),
    ]

    operations = [
    ]
