# Generated by Django 5.0.4 on 2024-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_merge_20240609_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='anotacoes_internas',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
    ]
